/*
test_dbf - setup on json, may change at any time
*/

FUNCTION test_Setup()

   LOCAL cTxt := ""

   cTxt += '[' + hb_Eol()
   cTxt += '[ "LOGIN", [ false ] ],' + hb_Eol()

   cTxt += '[ "KEYLIST", [' + hb_Eol()
   cTxt += '[ "cDbfName",    "cFieldName", "nBrowseOrder"],' + hb_Eol()
#ifdef DLGAUTO_AS_LIB
   cTxt += '[ "JPAGENDA",    "IDAGENDA", 2 ],' + hb_Eol()
   cTxt += '[ "JPCADASTRO",  "IDCADASTRO", 2 ],' + hb_Eol()
   cTxt += '[ "JPCONTABIL",  "IDCONTABIL", 2 ],' + hb_Eol()
   cTxt += '[ "JPCTCONTA",   "IDCTCONTA", 2 ],' + hb_Eol()
   cTxt += '[ "JPESTOQUE",   "IDESTOQUE", 2 ],' + hb_Eol()
   cTxt += '[ "JPFINAN",     "IDFINAN", 2 ],' + hb_Eol()
   cTxt += '[ "JPFISCAL",    "IDFISCAL", 2 ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO",   "IDIMPOSTO", 2 ],' + hb_Eol()
   cTxt += '[ "JPITEM",      "IDPRODUTO", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABCADSTA", "IDCADSTA", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABCFOP",   "IDCFOP",     2 ],' + hb_Eol()
   cTxt += '[ "JPTABCIDADE", "IDCIDADE",   2 ],' + hb_Eol()
   cTxt += '[ "JPTABICMCST", "IDICMCST", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABIPICST", "IDIPICST", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABORIGEM", "IDORIGEM", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABPISCST", "IDPISCST", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABPISENQ", "IDPISENQ", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABPORTADOR", "IDPORTADOR",   2 ],' + hb_Eol()
   cTxt += '[ "JPTABPRODEP", "IDPRODEP", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABPROLOC", "IDPROLOC", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABPROGRU", "IDPROGRU", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABPROSEC", "IDPROSEC", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABTRICAD",  "IDTRICAD", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABTRIEMP", "IDTRIEMP", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABTRIUF", "IDTRIUF", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABTRIPRO", "IDTRIPRO", 2 ],' + hb_Eol()
   cTxt += '[ "JPTABUF",     "IDUF",   2 ],' + hb_Eol()
   cTxt += '[ "JPTABUNIDADE", "IDUNIDADE",   2 ],' + hb_Eol()
   cTxt += '[ "JPTRANSACAO", "IDTRANSACAO",   2 ],' + hb_Eol()
   cTxt += '[ "JPVENDEDOR", "IDVENDEDOR", 2 ],' + hb_Eol()
#endif
   cTxt += '[ "DBCLIENT",    "IDCLIENT",   2 ],' + hb_Eol()
   cTxt += '[ "DBPRODUCT",   "IDPRODUCT",  2 ],' + hb_Eol()
   cTxt += '[ "DBUNIT",      "IDUNIT",     2 ],' + hb_Eol()
   cTxt += '[ "DBSELLER",    "IDSELLER",   2 ],' + hb_Eol()
   cTxt += '[ "DBBANK",      "IDBANK",     2 ],' + hb_Eol()
   cTxt += '[ "DBGROUP",     "IDGROUP",    2 ],' + hb_Eol()
   cTxt += '[ "DBSTOCK",     "IDSTOCK"       ],' + hb_Eol()
   cTxt += '[ "DBFINANC",    "IDFINANC"      ],' + hb_Eol()
   cTxt += '[ "DBSTATE",     "IDSTATE",    2 ],' + hb_Eol()
   cTxt += '[ "DBTICKET",    "IDTICKET"      ],' + hb_Eol()
   cTxt += '[ "DBTICKETPRO", "IDTICKETPRO"   ],' + hb_Eol()
   cTxt += '[ "DBDBF",       "IDDBF",      2 ],' + hb_Eol()
   cTxt += '[ "DBFIELDS",    "IDFIELD",    2 ]' + hb_Eol()
   cTxt += ']],' + hb_Eol()

   cTxt += '[ "SEEKLIST",[' + hb_Eol()
   cTxt += '[ "cDbfOrigin", "cFieldName", "cDbfTarget", "cFieldTarget", "cFieldShow" ],' + hb_Eol()
#ifdef DLGAUTO_AS_LIB
   cTxt += '[ "JPCADASTRO", "CDTRICAD", "JPTABTRICAD", "IDTRICAD", "TRICADNOME" ],' + hb_Eol()
   cTxt += '[ "JPCADASTRO", "CDVENDEDOR", "JPVENDEDOR", "IDVENDEDOR", "VDNOME" ],' + hb_Eol()
   cTxt += '[ "JPCADASTRO", "CDPORTADOR", "JPTABPORTADOR", "IDPORTADOR", "PORTNOME" ],' + hb_Eol()
   cTxt += '[ "JPCADASTRO", "CDTRANSP", "JPTRANSP", "IDTRANSP", "TPNOME" ],' + hb_Eol()
   cTxt += '[ "JPCADASTRO", "CDTRICAD", "JPTABTRICAD", "IDTRICAD", "TRICADNOME" ],' + hb_Eol()
   cTxt += '[ "JPCADASTRO", "CDSTATUS", "JPTABCADSTA", "IDCADSTA", "CADSTANOME" ],' + hb_Eol()
   cTxt += '[ "JPTABCIDADE", "CIUF", "JPTABUF", "IDUF", "UFNOME" ],' + hb_Eol()
   cTxt += '[ "JPTABUF", "UFTRIUF", "JPTABTRIUF", "IDTRIUF", "TRIUFNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMTRANSACAO",  "JPTRANSACAO",  "IDTRANSACAO",  "TRNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMTRIUF",  "JPTABTRIUF",  "IDTRIUF",  "TRIUFNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMTRICAD", "JPTABTRICAD", "IDTRICAD", "TRICADNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMTRIPRO", "JPTABTRIPRO", "IDTRIPRO", "TRIPRONOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMCFOP",   "JPTABCFOP",   "IDCFOP", "CFOPNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMORIGEM", "JPTABORIGEM", "IDORIGEM", "ORIGEMNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMIPICST", "JPTABIPICST", "IDIPICST", "IPICSTNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMICMCST", "JPTABICMCST", "IDICMCST", "ICMCSTNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMCOFCST", "JPTABCOFCST", "IDCOFCST", "COFCSTNOME" ],' + hb_Eol()
   cTxt += '[ "JPIMPOSTO", "IMPISCST", "JPTABCOFCST", "IDCOFCST", "COFCSTNOME" ],' + hb_Eol()
#endif
   cTxt += '[ "DBCLIENT",   "CLSELLER",   "DBSELLER",   "IDSELLER",     "SENAME" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT",   "CLBANK",     "DBBANK",     "IDBANK",       "BANAME" ],' + hb_Eol()
   cTxt += '[ "DBTICKET",   "TICLIENT",   "DBCLIENT",   "IDCLIENT",     "CLNAME" ],' + hb_Eol()
   cTxt += '[ "xxxDBCLIENT",   "CLSTATE",    "DBSTATE",    "IDSTATE",      "STNAME" ],' + hb_Eol()
   cTxt += '[ "DBPRODUCT",  "IEUNIT",     "DBUNIT",     "IDUNIT",       "UNNAME" ],' + hb_Eol()
   cTxt += '[ "DBSTOCK",    "STCLIENT",   "DBCLIENT",   "IDCLIENT",     "CLNAME" ],' + hb_Eol()
   cTxt += '[ "DBSTOCK",    "STPRODUCT",  "DBPRODUCT",  "IDPRODUCT",    "PRNAME" ],' + hb_Eol()
   cTxt += '[ "DBSTOCK",    "STGROUP",    "DBGROUP",    "IDGROUP",      "GRNAME" ],' + hb_Eol()
   cTxt += '[ "DBFINANC",   "FICLIENT",   "DBCLIENT",   "IDCLIENT",     "CLNAME" ],' + hb_Eol()
   cTxt += '[ "DBFINANC",   "FIBANK",     "DBBANK",     "IDBANK",       "BANAME" ]' + hb_Eol()
   cTxt += ']],' + hb_Eol()

   cTxt += '[ "BROWSELIST",[' + hb_Eol()
   cTxt += '[ "cDbfOrigin",  "cFieldName", "cDbfTarget", "nOrder", "cFieldTarget", "cTargetKey", "lEdit", "cTitle" ],' + hb_Eol()
   cTxt += '[ "DBTICKET",    "IDTICKET",   "DBTICKETPRO",2,        "TPTICKET",     "IDTICKEDPRO",false,   "PROD LIST" ],' + hb_Eol()
   cTxt += '[ "DBDBF",       "NAME",       "DBFIELDS",   2,        "DBF",          "IDFIELD",    false,   "DBF LIST" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT",    "IDCLIENT",   "DBFINANC",   2,        "FICLIENT",     "IDFINANC",   true,    "FINANC LIST" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT",    "IDCLIENT",   "DBSTOCK",    2,        "STCLIENT",     "IDSTOCK",    false,   "STOCK LIST" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT",    "IDCLIENT",   "DBTICKET",   2,        "TICLIENT",     "IDTICKET",   false,   "TICKET LIST" ]' + hb_Eol()
   cTxt += ']],' + hb_Eol()

   cTxt += '[ "TYPELIST",[' + hb_Eol()
   cTxt += '[ "cDbfName", "cFieldName", "cType",      "aListMinMax" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT", "CLSTATE",    "COMBOBOX",   ["AC","RS","SP","RJ","PR","RN"] ],' + hb_Eol()
   cTxt += '[ "DBCLIENT", "CLSTATUS",   "CHECKBOX" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT", "CLDATE",     "DATEPICKER" ],' + hb_Eol()
   cTxt += '[ "DBFINANC", "FIDATTOPAY", "DATEPICKER" ],' + hb_Eol()
   cTxt += '[ "DBCLIENT", "CLPAYTERM",  "SPINNER",     [0,120] ]' + hb_Eol()
   cTxt += ']]' + hb_Eol()
   cTxt += ']' + hb_Eol()

   RETURN cTxt
